name: cd

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GIT_HUB_ACTIONS }}
          project_id: incantation-chanting-server
      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev
          docker build -t asia-northeast1-docker.pkg.dev/incantation-chanting-server/incantation-chanting-server/incantatio-chanting-server:${{ github.ref_name }} .
          docker push asia-northeast1-docker.pkg.dev/incantation-chanting-server/incantation-chanting-server/incantatio-chanting-server:${{ github.ref_name }}

  deploy:
    name: Deploy to cloud run
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GIT_HUB_ACTIONS }}
          project_id: incantation-chanting-server
      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy
          ${{ github.event.repository.name }}
          --project incantation-chanting-server
          --image asia-northeast1-docker.pkg.dev/incantation-chanting-server/incantation-chanting-server/incantatio-chanting-server:${{ github.ref_name }} 
          --region asia-northeast1
          --port 8000
          --max-instances 4
          --allow-unauthenticated
          --quiet
