name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
